
## Nivell 2

Treballem els conceptes de l'estructura d'una matriu, Broadcasting, indexació, Mask..

- Exercici 4

Mostreu-me amb exemples de diferents matrius, la regla fonamental de Broadcasting que diu : "les matrius es poden transmetre / broadcast si les seves dimensions coincideixen o si una de les matrius té una mida d'1".

In [2]:
import numpy as np


a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

Para esto me he revisado la información que hay en la documentación oficial de numpy:

https://numpy.org/doc/stable/user/theory.broadcasting.html#array-broadcasting-in-numpy

Básicamente el broadcasting es el sistema de que cuando tú le haces hacer una operación de dos arrays entre sí, qué hace numpy con su vida. En especial cuando no tienen la misma forma.

La forma más sencilla es que mira, que si le mandas a operar y el array tiene dimensión 0 pues todos por ese número y ya está. También que tengan la misma forma. Por ejemplo:

In [3]:
j = b * a
j

array([ 42,  84, 126, 168, 210])

o que tengan exactamente la misma forma:

In [6]:
k = c * c
k

array([[ 1,  4,  9],
       [16, 25, 36]])

(que curiosa forma de poner números cuadrados) 

ahora bien, suponte que tenemos dos matrices de dimensión 1. Si las sumamos o multiplicamos ocurrirá lo siguiente: 

In [7]:
b = np.array([1, 2, 3, 4, 5])
e = np.array([1, 2, 3, 4, 5, 6])
b+e

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

Nos da error porque la forma no coincide, no sabe con qué sumar el sexto número, y no se lo va a inventar numpy. Para hacer esa suma tendríamos que girar el primer array (o el segundo y entonces sumarlos. Y claro, al sumarlos lo que hará es estirar los valores de uno y otro lado, combinándolos y creando una matriz de 5x6 (o de 6x5)

En el ejemplo de la documentación de numpy 


In [9]:
b = np.array([1, 2, 3, 4, 5])
e = np.array([1, 2, 3, 4, 5, 6])
k = b.reshape(5,1)
k + e

array([[ 2,  3,  4,  5,  6,  7],
       [ 3,  4,  5,  6,  7,  8],
       [ 4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10, 11]])