## Nivell 1

Treballem els conceptes de l'estructura d'una matriu, dimensió, eixos i la vectorització que ens permet reduir l'ús de for loops en operacions aritmètiques o matemàtiques..

- Exercici 3

Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.


In [9]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
               [1, 5, 3, 4, 5],
               [1, 2, 6, 4, 5],
               [1, 2, 3, 7, 7],
               [5, 2, 3, 4, 5]])

print(arr)

[[1 2 3 4 5]
 [1 5 3 4 5]
 [1 2 6 4 5]
 [1 2 3 7 7]
 [5 2 3 4 5]]


Aquí aprendo cómo colocar de forma "visual" una matriz. Para hacer los máximos y mínimos es arr.max() y para hacerlo por ejes es arr.max(axis=0) o arr.max(axis=1)

In [6]:
print(arr.max())

7


In [10]:
print(arr.max(axis=0))

[5 5 6 7 7]


In [11]:
print(arr.max(axis=1))

[5 5 6 7 5]


Tuve que hacer un par de cambios para que la matriz no tuviera los máximos por ejes iguales. Ahora sí puede verse más claramente que el eje 0 son las columnas y el eje 1 son las filas en este tipo de representación. 