## Nivell 2

Treballem els conceptes de l'estructura d'una matriu, Broadcasting, indexació, Mask..

### Exercici 6

Mask la matriu anterior, realitzeu un càlcul booleà vectoritzat, agafant cada element i comprovant si es divideix uniformement per quatre.

Això retorna una matriu de mask de la mateixa forma amb els resultats elementals del càlcul.


In [2]:
import numpy as np
rng = np.random.RandomState(13)
np_matrix = np.matrix(rng.randint(0, high=9, size=(5, 5), dtype=int))
np_matrix

matrix([[2, 0, 0, 6, 2],
        [4, 3, 4, 2, 6],
        [5, 4, 2, 0, 3],
        [5, 3, 6, 5, 1],
        [2, 8, 8, 6, 2]])

Vuelvo a tomar lo que hice en el ejercicio anterior, al usar el random con otra semilla, toma otros valores. 

La máscara es un concepto que se utiliza bastante en dibujo por ordenador y, por lo que veo es aplicable a este tipo de matrices. Basta hacer una comprobación y numpy generará una matriz del mismo tamaño pero lleno de Trues y Falses en función de si la comprobación es correcta.  En este caso, para comprobar si X es divisible por cuatro hay que ver que el resto es 0 usando el módulo. X%4 == 0

Esto viene aquí explicado: https://www.w3schools.com/python/numpy/numpy_array_filter.asp

In [3]:
matrizMascara = np_matrix%4==0
matrizMascara

matrix([[False,  True,  True, False, False],
        [ True, False,  True, False, False],
        [False,  True, False,  True, False],
        [False, False, False, False, False],
        [False,  True,  True, False, False]])

Debido a que está muy entrelazado voy a aprovechar a hacer el Ejercicio 7 

---

### Exercici 7

A continuació, utilitzeu aquesta màscara per indexar a la matriu de números original. Això fa que la matriu perdi la seva forma original, reduint-la a una dimensió, però encara obteniu les dades que esteu cercant.

Una vez tienes una máscara (una matriz con valores true-false) puedes conseguir un array sólo con los valores que sean true, lo que tiene pinta de poder ahorrar memoria. Eso sí, como menciona el enunciado ya no hay resto de forma original de la matriz. Para eso le decimos "array[array máscara]"


In [4]:
np_matrix[matrizMascara]

matrix([[0, 0, 4, 4, 4, 0, 8, 8]])

In [5]:
np_matrix[!matrizMascara]

SyntaxError: invalid syntax (<ipython-input-5-a61a7702a8af>, line 1)

Quería comprobar si se puede hacer el inverso así de fácil, pero iba a ser mucho. Supongo que con dos líneas se puede hacer

In [10]:
matrizNoMascara  = !matrizMascara
print(matrizNoMascara)
np_matrix[matrizNoMascara]

['"matrizMascara" no se reconoce como un comando interno o externo,', 'programa o archivo por lotes ejecutable.']


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Pues parec que así tampoco. 

In [11]:
matrizNoMascara = not matrizMascara

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [14]:
matrizNoMascara = matrizMascara == False 
matrizNoMascara

matrix([[ True, False, False,  True,  True],
        [False,  True, False,  True,  True],
        [ True, False,  True, False,  True],
        [ True,  True,  True,  True,  True],
        [ True, False, False,  True,  True]])

Finalmente. Al final había que hacer una comparación con false. Así que se podría hacer el array contrario de esta forma:


In [16]:
np_matrix[matrizMascara==False]



matrix([[2, 6, 2, 3, 2, 6, 5, 2, 3, 5, 3, 6, 5, 1, 2, 6, 2]])

╰(*°▽°*)╯