## Nivell 2

Treballem els conceptes de l'estructura d'una matriu, Broadcasting, indexació, Mask..

- Exercici 5

Utilitza la Indexació per extreure els valors d'una columna i una fila de la matriu. I suma els seus valors.

In [1]:
import numpy as np

Tomo la matriz a partir de lo que [ha hecho mi compañero Leo](https://github.com/leobioinf0/imatges_numpy/blob/master/S03_T02_Estructura_duna_Matriu.ipynb) para hacer una matriz muy chula de base:

In [2]:
rng = np.random.RandomState(123)
np_matrix = np.matrix(rng.randint(0, high=9, size=(5, 5), dtype=int))
np_matrix

matrix([[2, 2, 6, 1, 3],
        [6, 1, 0, 1, 0],
        [0, 3, 4, 0, 0],
        [4, 1, 7, 3, 2],
        [4, 7, 2, 4, 8]])

Para tomar trozos de una matriz de array hay que usar lo que el w3c llama "slicing" o "rebanado". Esto se hace para tomar trozos de arrays gordos. Aquí lo explican más https://www.w3schools.com/python/numpy/numpy_array_slicing.asp

Que tu dices, sirve para tomar "columnas", "filas" pero también puede ser "hazme una matriz con los elementos que estén en fila y columna impar" y te lo puede sacar

        Slicing arrays

        Slicing in python means taking elements from one given index to another given index.

        We pass slice instead of index like this: [start:end].

        We can also define the step, like this: [start:end:step].

        If we don't pass start its considered 0

        If we don't pass end its considered length of array in that dimension

        If we don't pass step its considered 1

In [3]:
trozoMatriz= np_matrix[::2,::2]
trozoMatriz

matrix([[2, 6, 3],
        [0, 4, 0],
        [4, 2, 8]])

No me puedo creer que eso funcionara a la primera. Vamos a volver al ejercicio y sacar una columnay una fila al azar. Porque se puede

In [11]:
fila = np_matrix[rng.randint(0,4),:]
fila

matrix([[2, 2, 6, 1, 3]])

In [13]:
columna = np_matrix[:,rng.randint(0,4)]
columna

matrix([[2],
        [6],
        [0],
        [4],
        [4]])

Tenemos dos alternativas de suma, podemos hacer la suma con el expandido o podemos girar una de las dos matrices (la segunda) para que nos salga un array. O incluso podemos sumarlo todo a piñon y tener el mega total. Vamos a hacer las 3 opciones

In [14]:
fila.sum()+columna.sum()

30

Sumar todos los valores era fácil, claro. 

In [18]:
columnaEnFila = columna.reshape(5)
columnaEnFila

matrix([[2, 6, 0, 4, 4]])

In [19]:
fila+columnaEnFila

matrix([[4, 8, 6, 5, 7]])

Esta sería la opción de girar la columna y sumarle la fila. Esto sólo es posible porque la matriz original es cuadrada. 

In [20]:
fila+columna

matrix([[ 4,  4,  8,  3,  5],
        [ 8,  8, 12,  7,  9],
        [ 2,  2,  6,  1,  3],
        [ 6,  6, 10,  5,  7],
        [ 6,  6, 10,  5,  7]])

Esta es la opción den hacer el broadcast. Nótese que el array anterior en este caso es la diagonal de valores. Por lo visto para hacer eso existe np.diagonal(array). Probémoslo ya que estamos. https://numpy.org/doc/stable/reference/generated/numpy.diagonal.html

In [21]:
np.diagonal(fila+columna)

array([4, 8, 6, 5, 7])

La única diferencia que veo es que el objeto es un array y no una matrix peeero funciona = D